### PR TITLE
Add docker example php 7.2

### PR DESCRIPTION
**Pull request by themakunga**
Added docker folder with PHP 7.2.19 and tested against the other examples, it is not necessary to make other changes to the main plugin.

### CODE REVIEW

**Comment by a1b4** [comment]
@TheYakuza Can you add a description?, explaining what change and why, this is important to remember in the future the reason why we did some changes.

**Review by a1b4 — CHANGES_REQUESTED** [review]
@TheYakuza Can you add a description?, explaining what change and why, this is important to remember in the future the reason why we did some changes.

**Comment by themakunga** [comment]
> @TheYakuza Can you add a description?, explaining what change and why, this is important to remember in the future the reason why we did some changes.

@a1b4  Done 👌

**Review by a1b4 — APPROVED** [review]
nice work! 🎉

**Pull request merged**
